version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "mix"
    directory: "/mailglass_admin"
    schedule:
      interval: "weekly"
  - package-ecosystem: "mix"
    directory: "/mailglass_inbound"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/dev/toolchain"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/reference/demo_app"
    schedule:
      interval: "weekly"
