%{
  # Every tuple inherits this ownership and expiry.  The checker treats the
  # metadata as part of every record and rejects an expired policy.
  owner: "maintainers",
  reason: "measured pre-ratchet complexity; must only decrease",
  expires_on: ~D[2026-12-31],
  # {file, function, check, maximum_score, maximum_occurrences}
  credo: [
    {"lib/mailglass/adapters/fake.ex", "Mailglass.Adapters.Fake.trigger_event",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/compliance/unsubscribe.ex", "Mailglass.Compliance.Unsubscribe.private_ipv4?",
     "Credo.Check.Refactor.CyclomaticComplexity", 10, 1},
    {"lib/mailglass/compliance/unsubscribe.ex", "Mailglass.Compliance.Unsubscribe.validate_host!",
     "Credo.Check.Refactor.CyclomaticComplexity", 11, 1},
    {"lib/mailglass/deliverability.ex", "Mailglass.Deliverability.fetch_dkim_selectors",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/deliverability/spf.ex", "Mailglass.Deliverability.SPF.parse_term",
     "Credo.Check.Refactor.CyclomaticComplexity", 15, 1},
    {"lib/mailglass/deliverability/spf.ex", "Mailglass.Deliverability.SPF.resolve_nested_spf",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/events/reconciler.ex", "Mailglass.Events.Reconciler.attempt_link",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/installer/apply.ex", "Mailglass.Installer.Apply.apply_create_file",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/installer/apply.ex", "Mailglass.Installer.Apply.apply_ensure_block",
     "Credo.Check.Refactor.CyclomaticComplexity", 14, 1},
    {"lib/mailglass/installer/apply.ex", "Mailglass.Installer.Apply.apply_ensure_block",
     "Credo.Check.Refactor.Nesting", 5, 1},
    {"lib/mailglass/installer/apply.ex", "Mailglass.Installer.Apply.apply_ensure_snippet",
     "Credo.Check.Refactor.CyclomaticComplexity", 10, 1},
    {"lib/mailglass/installer/apply.ex", "Mailglass.Installer.Apply.apply_ensure_snippet",
     "Credo.Check.Refactor.Nesting", 4, 1},
    {"lib/mailglass/installer/apply.ex", "Mailglass.Installer.Apply.validate_preflight",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/migration_generator.ex", "Mailglass.MigrationGenerator.generate_legacy_repair!",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/migrations/postgres/v06.ex", "Mailglass.Migrations.Postgres.V06.down",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/migrations/postgres/v06.ex", "Mailglass.Migrations.Postgres.V06.up",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/outbound.ex", "Mailglass.Outbound.do_deliver_many",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/outbound/persistence.ex", "Mailglass.Outbound.Persistence.resolve_mailable",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/outbound/routes.ex", "Mailglass.Outbound.Routes.resolve_async",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/rate_limiter/atomic_bucket.ex",
     "Mailglass.RateLimiter.AtomicBucket.consume_existing", "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/suppression/resync.ex", "Mailglass.Suppression.Resync.candidates_for_page",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/suppression_store/ecto.ex", "Mailglass.SuppressionStore.Ecto.check",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/suppression_store/ecto.ex", "Mailglass.SuppressionStore.Ecto.fetch_entries",
     "Credo.Check.Refactor.CyclomaticComplexity", 17, 1},
    {"lib/mailglass/suppression_store/ets.ex", "Mailglass.SuppressionStore.ETS.check",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/tracking/rewriter.ex", "Mailglass.Tracking.Rewriter.collect_head_hrefs",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/tracking/rewriter.ex", "Mailglass.Tracking.Rewriter.rewrite_anchor",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/tracking/token.ex", "Mailglass.Tracking.Token.verify_click",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/webhook/ingest.ex", "Mailglass.Webhook.Ingest.update_projections_for_each",
     "Credo.Check.Refactor.CyclomaticComplexity", 10, 1},
    {"lib/mailglass/webhook/ingest.ex", "Mailglass.Webhook.Ingest.update_projections_for_each",
     "Credo.Check.Refactor.Nesting", 4, 1},
    {"lib/mailglass/webhook/providers/postmark.ex",
     "Mailglass.Webhook.Providers.Postmark.verify_basic_auth!",
     "Credo.Check.Refactor.CyclomaticComplexity", 10, 1},
    {"lib/mailglass/webhook/providers/postmark.ex",
     "Mailglass.Webhook.Providers.Postmark.verify_basic_auth!", "Credo.Check.Refactor.Nesting", 4,
     1},
    {"lib/mailglass/webhook/providers/postmark.ex",
     "Mailglass.Webhook.Providers.Postmark.verify_ip_allowlist!", "Credo.Check.Refactor.Nesting", 3,
     1},
    {"lib/mailglass/webhook/providers/ses.ex",
     "Mailglass.Webhook.Providers.SES.reject_oversized_content_length!",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mailglass/webhook/reconciler.ex", "Mailglass.Webhook.Reconciler.attempt_reconcile",
     "Credo.Check.Refactor.Nesting", 3, 2},
    {"lib/mailglass/webhook/reconciler.ex", "Mailglass.Webhook.Reconciler.reconcile",
     "Credo.Check.Refactor.Nesting", 3, 2},
    {"lib/mailglass/webhook/replay.ex", "Mailglass.Webhook.Replay.update_projections_for_each",
     "Credo.Check.Refactor.CyclomaticComplexity", 11, 1},
    {"lib/mailglass/webhook/replay.ex", "Mailglass.Webhook.Replay.update_projections_for_each",
     "Credo.Check.Refactor.Nesting", 4, 1},
    {"lib/mix/tasks/mailglass.docs.check.ex", "Mix.Tasks.Mailglass.Docs.Check.leak_issues",
     "Credo.Check.Refactor.Nesting", 4, 1},
    {"lib/mix/tasks/mailglass.docs.check.ex",
     "Mix.Tasks.Mailglass.Docs.Check.preview_boundary_issues", "Credo.Check.Refactor.Nesting", 3,
     1},
    {"lib/mix/tasks/mailglass.docs.check.ex", "Mix.Tasks.Mailglass.Docs.Check.tier1_surface_issues",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mix/tasks/mailglass.docs.check.ex",
     "Mix.Tasks.Mailglass.Docs.Check.trust_boundary_issues", "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mix/tasks/mailglass.gen.inbound_route.ex",
     "Mix.Tasks.Mailglass.Gen.InboundRoute.add_route", "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mix/tasks/mailglass.publish.check.ex", "Mix.Tasks.Mailglass.Publish.Check.verify_deps",
     "Credo.Check.Refactor.CyclomaticComplexity", 13, 1},
    {"lib/mix/tasks/mailglass.publish.check.ex", "Mix.Tasks.Mailglass.Publish.Check.verify_deps",
     "Credo.Check.Refactor.Nesting", 4, 1},
    {"lib/mix/tasks/mailglass.publish.check.ex",
     "Mix.Tasks.Mailglass.Publish.Check.verify_linked_constraint", "Credo.Check.Refactor.Nesting",
     3, 1},
    {"lib/mix/tasks/mailglass.publish.check.ex",
     "Mix.Tasks.Mailglass.Publish.Check.verify_metadata",
     "Credo.Check.Refactor.CyclomaticComplexity", 16, 1},
    {"lib/mix/tasks/mailglass.publish.check.ex",
     "Mix.Tasks.Mailglass.Publish.Check.verify_required_files",
     "Credo.Check.Refactor.CyclomaticComplexity", 10, 1},
    {"lib/mix/tasks/mailglass.suppressions.resync.ex",
     "Mix.Tasks.Mailglass.Suppressions.Resync.run", "Credo.Check.Refactor.Nesting", 3, 1},
    {"lib/mix/tasks/mailglass.upgrade.v0_2.ex",
     "Mix.Tasks.Mailglass.Upgrade.V0_2.upgrade_swoosh_calls",
     "Credo.Check.Refactor.CyclomaticComplexity", 10, 1},
    {"lib/mix/tasks/mailglass.upgrade.v0_2.ex",
     "Mix.Tasks.Mailglass.Upgrade.V0_2.upgrade_swoosh_calls", "Credo.Check.Refactor.Nesting", 3, 1},
    {"mailglass_inbound/lib/mailglass_inbound/execution.ex",
     "MailglassInbound.Execution.discover_bound_mailbox", "Credo.Check.Refactor.Nesting", 3, 2},
    {"mailglass_inbound/lib/mailglass_inbound/execution.ex", "MailglassInbound.Execution.dispatch",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"mailglass_inbound/lib/mailglass_inbound/inbound_records/execution_run.ex",
     "MailglassInbound.InboundRecords.ExecutionRun.validate_outcome_shape",
     "Credo.Check.Refactor.CyclomaticComplexity", 15, 1},
    {"mailglass_inbound/lib/mailglass_inbound/inbound_records/replay_run.ex",
     "MailglassInbound.InboundRecords.ReplayRun.validate_outcome_shape",
     "Credo.Check.Refactor.CyclomaticComplexity", 10, 1},
    {"mailglass_inbound/lib/mailglass_inbound/ingress/persist.ex",
     "MailglassInbound.Ingress.Persist.insert_record", "Credo.Check.Refactor.Nesting", 3, 1},
    {"mailglass_inbound/lib/mailglass_inbound/ingress/providers/mailgun.ex",
     "MailglassInbound.Ingress.Providers.Mailgun.extract_attachments",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"mailglass_inbound/lib/mailglass_inbound/ingress/providers/mailgun.ex",
     "MailglassInbound.Ingress.Providers.Mailgun.extract_message_id",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"mailglass_inbound/lib/mailglass_inbound/ingress/providers/mailgun.ex",
     "MailglassInbound.Ingress.Providers.Mailgun.normalize_parsed",
     "Credo.Check.Refactor.CyclomaticComplexity", 10, 1},
    {"mailglass_inbound/lib/mailglass_inbound/ingress/providers/postmark.ex",
     "MailglassInbound.Ingress.Providers.Postmark.verify_ip_allowlist!",
     "Credo.Check.Refactor.Nesting", 3, 1},
    {"mailglass_inbound/lib/mailglass_inbound/ingress/providers/sendgrid.ex",
     "MailglassInbound.Ingress.Providers.Sendgrid.extract_parts", "Credo.Check.Refactor.Nesting", 3,
     1},
    {"mailglass_inbound/lib/mailglass_inbound/migrations/postgres/v02.ex",
     "MailglassInbound.Migrations.Postgres.V02.down", "Credo.Check.Refactor.Nesting", 3, 1},
    {"mailglass_inbound/lib/mailglass_inbound/migrations/postgres/v02.ex",
     "MailglassInbound.Migrations.Postgres.V02.up", "Credo.Check.Refactor.Nesting", 3, 1},
    {"mailglass_inbound/lib/mailglass_inbound/router/matcher.ex",
     "MailglassInbound.Router.Matcher.match", "Credo.Check.Refactor.Nesting", 3, 1},
    {"mailglass_inbound/lib/mailglass_inbound/s3_fetcher/retry.ex",
     "MailglassInbound.S3Fetcher.Retry.do_attempt", "Credo.Check.Refactor.Nesting", 3, 1},
    {"test/scripts/required_checks_test.exs",
     "Mailglass.Scripts.RequiredChecksTest.parse_ci_green_needs_list",
     "Credo.Check.Refactor.CyclomaticComplexity", 10, 1},
    {"test/scripts/required_checks_test.exs",
     "Mailglass.Scripts.RequiredChecksTest.parse_ci_green_needs_list",
     "Credo.Check.Refactor.Nesting", 4, 1},
    {"test/support/ci_yaml.ex", "Mailglass.CIYaml.scan_include_line",
     "Credo.Check.Refactor.CyclomaticComplexity", 13, 1},
    {"test/support/installer_fixture_helpers.ex",
     "Mailglass.Test.InstallerFixtureHelpers.run_install!", "Credo.Check.Refactor.Nesting", 3, 1},
    {"test/support/suite_floor.ex", "Mailglass.TestSupport.SuiteFloor.print_report",
     "Credo.Check.Refactor.Nesting", 3, 1}
  ],
  # {package, file, strict_description, owner, reason, expires_on}
  dialyzer: [
    {".", "lib/mailglass/errors/batch_failed.ex",
     "Type mismatch with behaviour callback to type/1.", "core",
     "macro-generated Error callback typing", ~D[2026-12-31]},
    {".", "lib/mailglass/errors/batch_failed.ex",
     "Type mismatch with behaviour callback to retryable?/1.", "core",
     "macro-generated Error callback typing", ~D[2026-12-31]},
    {".", "lib/mailglass/tenancy/resolve_from_path.ex",
     "Function scope/2 only terminates with explicit exception.", "core",
     "intentional raising guard", ~D[2026-12-31]},
    {".", "lib/mix/tasks/mailglass.publish.check.ex",
     "Function fail_step/2 only terminates with explicit exception.", "release",
     "intentional task failure boundary", ~D[2026-12-31]},
    {".", "lib/mailglass/config.ex",
     "Function invalid_adapter_entry!/2 only terminates with explicit exception.", "core",
     "intentional configuration error boundary", ~D[2026-12-31]},
    {".", "lib/mailglass/deliverability/bimi.ex",
     "Type specification for analyze is a supertype of the success typing.", "core",
     "forward-compatible evidence map", ~D[2026-12-31]},
    {".", "lib/mailglass/optional_deps/gen_smtp.ex",
     "@spec for decode has more types than are returned by the function.", "core",
     "optional Erlang decoder typing", ~D[2026-12-31]},
    {".", "dev/mailglass/reference_host/operator_diagnosis_proof.ex",
     "Type specification for run is a supertype of the success typing.", "reference-host",
     "forward-compatible proof map", ~D[2026-12-31]},
    {".", "dev/mailglass/reference_host/operator_diagnosis_proof.ex",
     "Function MailglassAdmin.OptionalDeps.MailglassInbound.explain_routes/2 does not exist.",
     "reference-host", "soft-loaded sibling package", ~D[2026-12-31]},
    {".", "dev/mailglass/reference_host/operator_diagnosis_proof.ex",
     "Function MailglassAdmin.Components.mask_recipient/1 does not exist.", "reference-host",
     "soft-loaded sibling package", ~D[2026-12-31]},
    {".", "dev/mailglass/reference_host/webhook_operator_proof.ex",
     "Type specification for run is a supertype of the success typing.", "reference-host",
     "forward-compatible proof struct", ~D[2026-12-31]},
    {".", "dev/mailglass/reference_host/webhook_operator_proof.ex",
     "Function MailglassReferenceHostWeb.Router.call/2 does not exist.", "reference-host",
     "runtime-loaded proof router", ~D[2026-12-31]},
    {".", "test/support/reference_host/trust_runner_fixtures.ex",
     "Type specification for webhook_ingest_evidence is a supertype of the success typing.",
     "test-support", "forward-compatible proof fixture", ~D[2026-12-31]},
    {".", "lib/mailglass/operator/deliveries.ex",
     "Type specification for list_recent_deliveries is a supertype of the success typing.", "core",
     "Ecto projection typing artifact", ~D[2026-12-31]},
    {".", "lib/mailglass/operator/tenants.ex",
     "Invalid type specification for function list_tenants.", "core",
     "Ecto projection typing artifact", ~D[2026-12-31]}
  ]
}
