defmodule Mailglass.Installer.Templates do
  @moduledoc """
  Installer template helpers for owned files and managed shared-file patches.
  """

  @doc """
  Returns the generated mail context module source.
  """
  @spec mail_context_module(keyword()) :: String.t()
  def mail_context_module(opts \\ []) do
    app_module = Keyword.get(opts, :app_module, "MyApp")

    """
    defmodule #{app_module}.MailContext do
      @moduledoc \"\"\"
      Mailglass integration boundary for this host app.
      \"\"\"
    end
    """
  end

  @doc """
  Returns the snippet inserted into `router.ex` for the Mailglass admin surface.
  """
  @spec router_mount_snippet(keyword()) :: String.t()
  def router_mount_snippet(opts \\ []) do
    otp_app =
      opts
      |> Keyword.get(:app_module, "MyApp")
      |> Macro.underscore()

    """
        # Mailglass admin routes (dev-only; flip :dev_routes in config to expose).
        import MailglassAdmin.Router

        if Application.compile_env(:#{otp_app}, :dev_routes) do
          scope "/dev" do
            pipe_through :browser
            mailglass_admin_routes "/mail"
          end
        end
    """
  end

  @doc """
  Returns the snippet inserted into `router.ex` for the Mailglass webhook surface.
  """
  @spec webhook_mount_snippet(keyword()) :: String.t()
  def webhook_mount_snippet(_opts \\ []) do
    """
        # Mailglass webhook routes (Postmark + SendGrid).
        import Mailglass.Webhook.Router

        pipeline :mailglass_webhooks do
          plug :accepts, ["json"]
          # NO :browser, :fetch_session, :protect_from_forgery — webhooks
          # do not carry a session or participate in CSRF.
        end

        scope "/" do
          pipe_through :mailglass_webhooks
          mailglass_webhook_routes "/webhooks"
        end
    """
  end

  @doc """
  Marker line for the start of the managed endpoint webhook-parser block.
  """
  @spec endpoint_webhook_block_start() :: String.t()
  def endpoint_webhook_block_start, do: "# mailglass:start endpoint_webhook_parser"

  @doc """
  Marker line for the end of the managed endpoint webhook-parser block.
  """
  @spec endpoint_webhook_block_end() :: String.t()
  def endpoint_webhook_block_end, do: "# mailglass:end endpoint_webhook_parser"

  @doc """
  Returns the verbatim Plug.Parsers body_reader config block inserted into
  `endpoint.ex`.
  """
  @spec endpoint_webhook_parser_body() :: String.t()
  def endpoint_webhook_parser_body do
    """
    plug Plug.Parsers,
      parsers: [:json],
      pass: ["*/*"],
      json_decoder: Jason,
      body_reader: {Mailglass.Webhook.CachingBodyReader, :read_body, []},
      length: 10_000_000
    """
  end

  @doc """
  Anchor line used to insert router snippets.
  """
  @spec router_anchor() :: String.t()
  def router_anchor, do: "use Phoenix.Router"

  @doc """
  Marker line for the start of the managed runtime config block.
  """
  @spec runtime_block_start() :: String.t()
  def runtime_block_start, do: "# mailglass:start runtime"

  @doc """
  Marker line for the end of the managed runtime config block.
  """
  @spec runtime_block_end() :: String.t()
  def runtime_block_end, do: "# mailglass:end runtime"

  @doc """
  Returns the managed block body inserted into `runtime.exs`.
  """
  @spec runtime_config_body() :: String.t()
  def runtime_config_body do
    """
    config :mailglass,
      telemetry_prefix: [:mailglass],
      enable_preview: true
    """
  end

  @doc """
  Wraps a managed block body with explicit start/end markers.
  """
  @spec managed_block(String.t(), String.t(), String.t()) :: String.t()
  def managed_block(start_marker, end_marker, body) do
    """
    #{start_marker}
    #{String.trim_trailing(body)}
    #{end_marker}
    """
  end

  @doc """
  Returns the default mailable stub source.
  """
  @spec default_mailable(keyword()) :: String.t()
  def default_mailable(opts \\ []) do
    app_module = Keyword.get(opts, :app_module, "MyApp")

    """
    defmodule #{app_module}.Mail.DefaultMailable do
      @moduledoc \"\"\"
      Starter mailable generated by `mix mailglass.install`.
      \"\"\"

      use Mailglass.Mailable
    end
    """
  end

  @doc """
  Returns the starter layout template content.
  """
  @spec default_layout() :: String.t()
  def default_layout do
    """
    <html>
      <body>
        <main>
          <%%= @inner_content %>
        </main>
      </body>
    </html>
    """
  end

  @doc """
  Returns the generated Oban worker stub source.
  """
  @spec oban_worker_stub(keyword()) :: String.t()
  def oban_worker_stub(opts \\ []) do
    app_module = Keyword.get(opts, :app_module, "MyApp")

    """
    defmodule #{app_module}.Mail.Worker do
      @moduledoc \"\"\"
      Starter Oban worker stub generated by `mix mailglass.install`.
      \"\"\"

      use Oban.Worker, queue: :mailers

      @impl Oban.Worker
      def perform(_job), do: :ok
    end
    """
  end
end
