defmodule Mailglass.Events do
  @moduledoc """
  Append-only event writer. The only legitimate path to
  `mailglass_events`. Phase 6 `NoRawEventInsert` Credo check enforces
  that no other code calls `Repo.insert(%Event{})` or
  `Repo.insert_all("mailglass_events", ...)`.

  ## Public API

  - `append/1` — standalone audit write. Opens its own `Repo.transact/1`.
    Returns `{:ok, %Event{}}`. Use for admin actions, `mix
    mail.doctor` breadcrumbs, tenant provisioning — anything without
    a companion domain mutation.
  - `append_multi/3` — composable Ecto.Multi step. Use when writing
    an event alongside a Delivery insert or projection update.
    Returns an enriched `%Ecto.Multi{}`.

  ## Idempotency (PERSIST-03, MAIL-03 prevention)

  When `attrs` carries an `:idempotency_key`, both paths use the
  partial-unique-index conflict target:

      on_conflict: :nothing,
      conflict_target: {:unsafe_fragment, "(idempotency_key) WHERE idempotency_key IS NOT NULL"},
      returning: true

  `append/1` detects the conflict-replay case and re-fetches the
  existing row by `idempotency_key`. `append_multi/3` surfaces replay
  to the caller via a follow-up `Multi.run` step inspecting the
  returned event's `inserted_at`.

  ### The replay-detection sentinel: `inserted_at`, not `id`

  The accrue precedent (bigserial PK) detects replay via `id == nil`
  because Postgres auto-generates the id server-side; on conflict,
  no row is inserted, RETURNING yields nothing, and Ecto populates
  the struct with the client-side `nil` id. Mailglass uses UUIDv7
  (autogenerated client-side by the `Mailglass.Schema` macro), so
  the struct's `id` field is NEVER nil — Ecto has always filled it
  before sending to the DB. The sentinel that IS nil on conflict is
  any DB-defaulted column that only gets its value back via
  RETURNING: `inserted_at` (populated by the migration's
  `default: fragment("now()")`). Ecto issues #3132/#3910/#2694
  describe the same underlying behavior; the detection mechanic
  is just the column that tells the story.

  ## Auto-capture (D-05)

  When `:tenant_id` is not in `attrs`, `Mailglass.Tenancy.current/0`
  fills it. When `:trace_id` is not set, an OTel context probe fills
  it (nil-tolerant; the probe is guarded so the module compiles even
  when `:otel_propagator_text_map` is absent).

  ## Telemetry (D-04)

  Both paths (well, `append/1` directly; `append_multi/3` via the
  caller's `Repo.transact/1` call) emit
  `[:mailglass, :events, :append, :start | :stop | :exception]`.
  `:stop` metadata carries `inserted?: boolean` and
  `idempotency_key_present?: boolean` so downstream replay counters
  can hook without a second DB query.
  """

  use Boundary,
    deps: [Mailglass],
    exports: [Event, Reconciler]

  alias Mailglass.Events.Event
  alias Mailglass.Tenancy

  import Ecto.Query

  @type attrs :: %{
          optional(:type) => atom() | String.t(),
          optional(:delivery_id) => Ecto.UUID.t() | nil,
          optional(:occurred_at) => DateTime.t(),
          optional(:idempotency_key) => String.t() | nil,
          optional(:reject_reason) => atom() | nil,
          optional(:normalized_payload) => map(),
          optional(:metadata) => map(),
          optional(:tenant_id) => String.t(),
          optional(:trace_id) => String.t() | nil,
          optional(:needs_reconciliation) => boolean()
        }

  @doc """
  Standalone audit append — opens a transaction, inserts, translates
  45A01 errors. Returns `{:ok, %Event{}}` on success (including replay).
  """
  @doc since: "0.1.0"
  @spec append(attrs()) :: {:ok, Event.t()} | {:error, term()}
  def append(attrs) when is_map(attrs) do
    normalized = normalize(attrs)

    meta = %{
      tenant_id: normalized[:tenant_id],
      idempotency_key_present?: is_binary(Map.get(normalized, :idempotency_key))
    }

    Mailglass.Telemetry.events_append_span(meta, fn ->
      Mailglass.Repo.transact(fn -> do_insert(normalized) end)
    end)
  end

  @doc """
  Appends an insert step to an existing `Ecto.Multi`. The caller owns
  the transact/commit lifecycle. Replay observability is the caller's
  responsibility (add a `Multi.run` step inspecting
  `event.inserted_at == nil` — see moduledoc "The replay-detection
  sentinel" for why `inserted_at`, not `id`).

  ## Function-form attrs (I-03, Phase 3)

  When `attrs` is a 1-arity function, it is called inside a `Multi.run`
  step with the prior `changes` map. This allows callers to reference a
  prior step's result (e.g. a just-inserted `Delivery`'s `:id`) in the
  event's `:delivery_id` field. The step producing the attrs map is named
  `:"<name>_attrs"` and the insert step is named `name`.

  ## Examples

      # Map form (existing):
      Events.append_multi(multi, :queued, %{type: :queued, delivery_id: id})

      # Function form (new in Phase 3):
      Events.append_multi(multi, :queued, fn %{delivery: d} ->
        %{type: :queued, delivery_id: d.id}
      end)
  """
  @doc since: "0.1.0"
  @spec append_multi(Ecto.Multi.t(), atom(), attrs() | (map() -> attrs())) :: Ecto.Multi.t()
  def append_multi(multi, name, attrs) when is_atom(name) and is_map(attrs) do
    normalized = normalize(attrs)
    changeset = Event.changeset(normalized)
    Ecto.Multi.insert(multi, name, changeset, insert_opts(normalized))
  end

  def append_multi(multi, name, attrs) when is_atom(name) and is_function(attrs, 1) do
    # Function form (Phase 3): compose via a Multi.run step that produces
    # the attrs map from prior Multi changes, then feeds it into the insert.
    # Matches Multi.insert/4 and Oban.insert/2 function-form conventions —
    # callers can reference a prior step's result (e.g. a just-inserted
    # Delivery's :id) in the event's :delivery_id field.
    attrs_name = String.to_atom(Atom.to_string(name) <> "_attrs")

    multi
    |> Ecto.Multi.run(attrs_name, fn _repo, changes -> {:ok, attrs.(changes)} end)
    |> Ecto.Multi.run(name, fn repo, changes ->
      raw = Map.fetch!(changes, attrs_name)
      normalized = normalize(raw)
      changeset = Event.changeset(normalized)
      opts = insert_opts(normalized)
      repo.insert(changeset, opts)
    end)
  end

  # D-05: auto-capture tenant_id + trace_id + occurred_at defaults.
  defp normalize(attrs) do
    attrs
    |> Map.new()
    |> Map.put_new_lazy(:tenant_id, &Tenancy.current/0)
    |> Map.put_new_lazy(:trace_id, &current_trace_id/0)
    |> Map.put_new_lazy(:occurred_at, &Mailglass.Clock.utc_now/0)
    |> Map.put_new(:normalized_payload, %{})
    |> Map.put_new(:metadata, %{})
  end

  # Optional OTel probe. Guarded — returns nil when OTel is absent.
  # Phase 1's OpenTelemetry gateway probes `:otel_tracer`; here we stay
  # conservative and just return nil until Phase 4 wires explicit trace
  # context plumbing through webhook ingestion.
  defp current_trace_id, do: nil

  # D-03: partial-unique-index conflict target REQUIRES the WHERE fragment
  # to match the index DDL character-for-character.
  defp insert_opts(%{idempotency_key: key}) when is_binary(key) do
    [
      on_conflict: :nothing,
      conflict_target: {:unsafe_fragment, "(idempotency_key) WHERE idempotency_key IS NOT NULL"},
      returning: true
    ]
  end

  defp insert_opts(_), do: [returning: true]

  # D-03: detect conflict-replay and fetch the existing row by
  # idempotency_key. The sentinel is `inserted_at: nil` (not `id: nil`)
  # because UUIDv7 is client-side autogenerated — the id field is
  # always populated before INSERT even when the DB ultimately skips
  # the row. `inserted_at` is DB-defaulted (`default: fragment("now()")`)
  # and only comes back via RETURNING, so it's nil on the ON CONFLICT
  # DO NOTHING skip.
  defp do_insert(%{idempotency_key: key} = attrs) when is_binary(key) do
    changeset = Event.changeset(attrs)

    case Mailglass.Repo.insert(changeset, insert_opts(attrs)) do
      {:ok, %Event{inserted_at: nil}} -> fetch_by_idempotency_key(key)
      {:ok, %Event{} = event} -> {:ok, event}
      {:error, _} = err -> err
    end
  end

  defp do_insert(attrs) do
    attrs
    |> Event.changeset()
    |> Mailglass.Repo.insert(insert_opts(attrs))
  end

  defp fetch_by_idempotency_key(key) do
    query = from(e in Event, where: e.idempotency_key == ^key, limit: 1)

    case Mailglass.Repo.one(Tenancy.scope(query)) do
      nil -> {:error, :idempotency_lookup_failed}
      event -> {:ok, event}
    end
  end
end
