defmodule Mailglass.Migrations.LegacyToy do
  @moduledoc false

  use Ecto.Migration

  @legacy_table "mailglass_events"

  @spec preflight!(module(), String.t(), Path.t(), module()) :: :ok
  def preflight!(repo, prefix, path, app_module) do
    expected_source = source(app_module)

    case File.read(path) do
      {:ok, ^expected_source} ->
        :ok

      {:ok, _source} ->
        Mix.raise("Installation blocked: legacy source is ambiguous; no migration was written")

      {:error, reason} ->
        Mix.raise(
          "Installation blocked: legacy source is unavailable (#{:file.format_error(reason)}); no migration was written"
        )
    end

    validate_catalog!(repo, prefix)
    :ok
  end

  @spec source(module()) :: String.t()
  def source(app_module) do
    """
    defmodule #{inspect(Module.concat([app_module, Repo, Migrations, MailglassInstall]))} do
      use Ecto.Migration

      def change do
        create table(:mailglass_events) do
          add :tenant_id, :string
          timestamps(type: :utc_datetime_usec)
        end
      end
    end
    """
  end

  @spec repair_up(keyword()) :: :ok
  def repair_up(opts) do
    prefix = Keyword.fetch!(opts, :prefix)
    quoted_prefix = inspect(prefix)

    execute("DROP TABLE #{quoted_prefix}.#{@legacy_table} RESTRICT")
    flush()
    Mailglass.Migration.up(opts)
    flush()
  end

  @spec repair_down(keyword()) :: :ok
  def repair_down(opts) do
    prefix = Keyword.fetch!(opts, :prefix)
    quoted_prefix = inspect(prefix)

    Mailglass.Migration.down(Keyword.put(opts, :version, 0))

    execute("""
    CREATE TABLE #{quoted_prefix}.#{@legacy_table} (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id character varying,
      inserted_at timestamp(6) without time zone NOT NULL,
      updated_at timestamp(6) without time zone NOT NULL
    )
    """)
  end

  defp validate_catalog!(repo, prefix) do
    attributes =
      query!(repo, prefix, """
      SELECT attname, pg_catalog.format_type(atttypid, atttypmod), attnotnull, attidentity,
             pg_catalog.pg_get_expr(adbin, adrelid)
      FROM pg_catalog.pg_attribute
      LEFT JOIN pg_catalog.pg_attrdef ON pg_attrdef.adrelid = pg_attribute.attrelid
        AND pg_attrdef.adnum = pg_attribute.attnum
      WHERE attrelid = ($1 || '.mailglass_events')::regclass
        AND attnum > 0 AND NOT attisdropped
      ORDER BY attnum
      """)

    expected_attributes = [
      ["id", "bigint", true, "d", nil],
      ["tenant_id", "character varying", false, <<0>>, nil],
      ["inserted_at", "timestamp(6) without time zone", true, <<0>>, nil],
      ["updated_at", "timestamp(6) without time zone", true, <<0>>, nil]
    ]

    constraints =
      query!(repo, prefix, """
      SELECT conname, contype, pg_catalog.pg_get_constraintdef(oid, true)
      FROM pg_catalog.pg_constraint
      WHERE conrelid = ($1 || '.mailglass_events')::regclass
      ORDER BY conname
      """)

    indexes =
      query!(repo, prefix, """
      SELECT indexname, indexdef
      FROM pg_catalog.pg_indexes
      WHERE schemaname = $1 AND tablename = 'mailglass_events'
      ORDER BY indexname
      """)

    rows = query_without_params!(repo, "SELECT count(*) FROM #{inspect(prefix)}.#{@legacy_table}")

    if attributes != expected_attributes or
         constraints != [["mailglass_events_pkey", "p", "PRIMARY KEY (id)"]] or
         indexes != [
           [
             "mailglass_events_pkey",
             "CREATE UNIQUE INDEX mailglass_events_pkey ON #{prefix}.mailglass_events USING btree (id)"
           ]
         ] do
      Mix.raise("Installation blocked: legacy catalog is ambiguous; no migration was written")
    end

    case rows do
      [[0]] ->
        :ok

      [[count]] when is_integer(count) and count > 0 ->
        Mix.raise("Installation blocked: legacy table is populated; no migration was written")

      _ ->
        Mix.raise("Installation blocked: legacy catalog is unavailable; no migration was written")
    end
  rescue
    _error in Postgrex.Error ->
      Mix.raise("Installation blocked: legacy catalog is unavailable; no migration was written")
  end

  defp query!(repo, prefix, query), do: query_with_params!(repo, query, [prefix])

  defp query_without_params!(repo, query), do: query_with_params!(repo, query, [])

  defp query_with_params!(repo, query, params) do
    case repo.query(query, params, log: false) do
      {:ok, %{rows: rows}} when is_list(rows) ->
        rows

      _ ->
        Mix.raise("Installation blocked: legacy catalog is unavailable; no migration was written")
    end
  end
end
