defmodule MailglassAdmin.AxeBaselineTest do
  @moduledoc """
  Fail-closed axe-violation baseline assertion (RATCHET-03, D-04).

  Phase 116: establishes and enforces the WCAG 2.2 AA axe-violation ratchet over
  the 9-cell baseline (3 surfaces × 3 themes), a near-clone of
  `ratchet_baseline_test.exs`.

  The committed baseline lives in `mailglass_admin/docs/axe-baseline.json`
  (sibling of `ui-baseline-scores.json`). It is regenerated by the screenshot-free
  producer `e2e/axe-baseline.spec.js`:

      cd mailglass_admin && PERSIST_AXE_BASELINE=1 npm run test:operator-browser -- axe-baseline.spec.js

  If this test fails with "missing cell", the producer scan was incomplete — run
  the producer to fill all 9 surface × theme cells.

  If it fails with a "(REGRESSION)" message like
  `inbound.dark: color-contrast 0 → 2 (REGRESSION)`, a surface gained axe
  violations relative to the committed baseline. Either fix the accessibility
  regression or, after a deliberate re-baseline, promote `current → prior` and
  re-run the producer so a fresh `current` is measured.
  """

  use ExUnit.Case, async: true

  # Two levels up from test/mailglass_admin/ → test/ → mailglass_admin/ → docs/
  # docs/ is outside priv/, so use __DIR__ relative path (not Application.app_dir).
  @axe_path Path.join([__DIR__, "..", "..", "docs", "axe-baseline.json"])

  @surfaces ["deliveries", "inbound", "preview"]
  @themes ["light", "dark", "system"]

  setup_all do
    assert File.exists?(@axe_path),
           "axe-baseline.json not found at #{@axe_path} — " <>
             "run the axe producer (e2e/axe-baseline.spec.js with " <>
             "PERSIST_AXE_BASELINE=1) to regenerate it."

    {:ok, baseline: Jason.decode!(File.read!(@axe_path))}
  end

  test "schema_version is present and supported", %{baseline: b} do
    assert b["schema_version"] == 1,
           "Expected schema_version 1, got #{inspect(b["schema_version"])}. " <>
             "The axe baseline schema is locked at 1 (distinct from the score " <>
             "baseline's 3). If upgrading the JSON format, bump schema_version " <>
             "and update this assertion."
  end

  test "all 9 surface × theme cells are present in both prior and current blocks",
       %{baseline: b} do
    missing =
      for block <- ["prior", "current"],
          surface <- @surfaces,
          theme <- @themes do
        cell = get_in(b, [block, "violations", surface, theme])
        if cell == nil, do: "#{block}.#{surface}.#{theme}", else: nil
      end
      |> Enum.reject(&is_nil/1)

    assert missing == [],
           "Missing cells (#{length(missing)}) in axe-baseline.json:\n" <>
             Enum.join(missing, "\n") <>
             "\nRun the axe producer to fill all 9 surface × theme cells in each block."
  end

  test "every present cell has a numeric total and a rules map in both blocks",
       %{baseline: b} do
    malformed =
      for block <- ["prior", "current"],
          surface <- @surfaces,
          theme <- @themes do
        cell = get_in(b, [block, "violations", surface, theme])

        cond do
          is_nil(cell) -> nil
          not is_integer(cell["total"]) -> "#{block}.#{surface}.#{theme}: total not integer"
          not is_map(cell["rules"]) -> "#{block}.#{surface}.#{theme}: rules not a map"
          true -> nil
        end
      end
      |> Enum.reject(&is_nil/1)

    assert malformed == [],
           "Malformed cells (#{length(malformed)}) in axe-baseline.json:\n" <>
             Enum.join(malformed, "\n")
  end

  test "only-forward ratchet: no cell or rule-id regresses the prior committed baseline",
       %{baseline: b} do
    # D-04 anti-vacuity guard — a forgotten current → prior promotion fails loudly here.
    assert b["prior"]["run_id"] != b["current"]["run_id"],
           "prior and current share run_id #{inspect(b["prior"]["run_id"])} — " <>
             "the re-scan was not promoted; this would be a vacuous self-comparison."

    compare_axe(b["prior"], b["current"])
  end

  test "system cell never carries more violations than the dark cell (A16-axe parity)",
       %{baseline: b} do
    # WR-02: Bucket-A A16-axe cites a "system cell <= dark cell" property. The
    # system theme follows prefers-color-scheme:dark (see axe-baseline.spec.js
    # emulatedColorScheme/themeQuery), so it must not regress relative to the
    # explicit dark cell — otherwise the system-mode surface is less accessible
    # than the dark surface it is meant to mirror. Assert per-total AND per-rule
    # over the `current` block so the ledger claim is genuinely enforced, not
    # vacuous.
    breaches =
      for surface <- @surfaces do
        dark = get_in(b, ["current", "violations", surface, "dark"])
        system = get_in(b, ["current", "violations", surface, "system"])

        cond do
          is_nil(dark) or is_nil(system) ->
            "#{surface}: missing dark/system cell (dark=#{inspect(dark)}, system=#{inspect(system)})"

          system["total"] > dark["total"] ->
            "#{surface}: system total #{system["total"]} > dark total #{dark["total"]} (PARITY BREACH)"

          true ->
            rule_breaches =
              for {rid, scount} <- system["rules"] || %{} do
                dcount = get_in(dark, ["rules", rid]) || 0

                if scount > dcount,
                  do: "#{surface}: system #{rid} #{scount} > dark #{dcount} (PARITY BREACH)",
                  else: nil
              end
              |> Enum.reject(&is_nil/1)

            if rule_breaches == [], do: nil, else: Enum.join(rule_breaches, "\n")
        end
      end
      |> Enum.reject(&is_nil/1)

    assert breaches == [],
           "A16-axe system<=dark parity breached (#{length(breaches)}):\n" <>
             Enum.join(breaches, "\n") <>
             "\nThe system theme follows prefers-color-scheme:dark and must not " <>
             "carry more axe violations than the explicit dark cell."
  end

  # ---------------------------------------------------------------------------
  # Verify-by-construction: the comparator must fail closed on a rising cell
  # total, a rising per-rule count, AND a new rule-id under a flat total.
  # ---------------------------------------------------------------------------

  defp nine_cells(fun) do
    %{
      "violations" =>
        Map.new(@surfaces, fn surface ->
          {surface, Map.new(@themes, fn theme -> {theme, fun.(surface, theme)} end)}
        end)
    }
  end

  defp flat_cell, do: %{"total" => 1, "rules" => %{"color-contrast" => 1}}

  test "compare_axe flags a rising cell total as a regression" do
    prior = nine_cells(fn _s, _t -> flat_cell() end)

    current =
      nine_cells(fn
        "inbound", "dark" -> %{"total" => 2, "rules" => %{"color-contrast" => 2}}
        _s, _t -> flat_cell()
      end)

    assert {:error, msg} = run_compare(prior, current)
    assert msg =~ "inbound.dark: total 1 → 2 (REGRESSION)"
  end

  test "compare_axe flags a NEW rule-id under a flat total (rule swap)" do
    prior = nine_cells(fn _s, _t -> flat_cell() end)

    # Same total (1) but the single failing node is now a different rule-id.
    current =
      nine_cells(fn
        "inbound", "dark" -> %{"total" => 1, "rules" => %{"aria-allowed-attr" => 1}}
        _s, _t -> flat_cell()
      end)

    assert {:error, msg} = run_compare(prior, current)
    assert msg =~ "inbound.dark: aria-allowed-attr 0 → 1 (REGRESSION)"
  end

  test "compare_axe flags a rising per-rule count even when total is unchanged" do
    prior =
      nine_cells(fn _s, _t ->
        %{"total" => 2, "rules" => %{"color-contrast" => 1, "aria-allowed-attr" => 1}}
      end)

    # Total stays 2 but color-contrast rises 1 → 2 while aria drops 1 → 0.
    current =
      nine_cells(fn
        "preview", "light" -> %{"total" => 2, "rules" => %{"color-contrast" => 2}}
        _s, _t -> %{"total" => 2, "rules" => %{"color-contrast" => 1, "aria-allowed-attr" => 1}}
      end)

    assert {:error, msg} = run_compare(prior, current)
    assert msg =~ "preview.light: color-contrast 1 → 2 (REGRESSION)"
  end

  test "compare_axe fails closed on a missing cell rather than coercing to total 0" do
    prior = nine_cells(fn _s, _t -> flat_cell() end)

    current =
      nine_cells(fn _s, _t -> flat_cell() end)
      |> update_in(["violations", "inbound"], &Map.delete(&1, "dark"))

    assert {:error, msg} = run_compare(prior, current)
    assert msg =~ "inbound.dark: missing cell"
  end

  test "compare_axe fails closed when a non-zero-total cell has a non-map rules map (WR-03)" do
    prior = nine_cells(fn _s, _t -> flat_cell() end)

    # A producer regression: same total but the rules map was dropped to nil.
    # Without the guard this slips through (total did not rise, and `cc["rules"]
    # || %{}` coerces nil to empty, so the per-rule loop finds nothing).
    current =
      nine_cells(fn
        "inbound", "dark" -> %{"total" => 1, "rules" => nil}
        _s, _t -> flat_cell()
      end)

    assert {:error, msg} = run_compare(prior, current)
    assert msg =~ "inbound.dark: current rules map missing/non-map"
  end

  test "compare_axe tolerates a non-map rules map only when the total is zero (no violations)" do
    # A clean cell is {total: 0, rules: {}}; a {total: 0, rules: nil} should not
    # trip the non-map guard, since there are no violations to diff.
    prior = nine_cells(fn _s, _t -> %{"total" => 0, "rules" => %{}} end)
    current = nine_cells(fn _s, _t -> %{"total" => 0, "rules" => nil} end)

    assert :ok = run_compare(prior, current)
  end

  test "compare_axe passes when every cell meets-or-beats prior" do
    prior = nine_cells(fn _s, _t -> %{"total" => 2, "rules" => %{"color-contrast" => 2}} end)
    # current improves: fewer violations everywhere.
    current = nine_cells(fn _s, _t -> %{"total" => 1, "rules" => %{"color-contrast" => 1}} end)

    assert :ok = run_compare(prior, current)
  end

  # Captures the comparator's pass/fail without aborting the test process, so the
  # verify-by-construction cases above can assert on the regression message.
  defp run_compare(prior, current) do
    compare_axe(prior, current)
    :ok
  rescue
    e in ExUnit.AssertionError -> {:error, e.message}
  end

  # ---------------------------------------------------------------------------
  # Live as of Phase 116 — called by the only-forward ratchet test above via
  # compare_axe(b["prior"], b["current"]). Adapted from the score baseline's
  # compare_baselines/2: fails closed on a missing cell, flags a rising cell
  # total, then diffs the per-rule map so a rule whose count rises OR a rule-id
  # newly present in current (pcount defaults to 0) regresses even under a flat
  # total (D-04 "rule swap under flat total").
  # ---------------------------------------------------------------------------
  defp compare_axe(prior, current) do
    regressions =
      for surface <- @surfaces, theme <- @themes do
        pc = get_in(prior, ["violations", surface, theme])
        cc = get_in(current, ["violations", surface, theme])

        cond do
          # Fail closed on a missing cell rather than coercing to {total: 0} —
          # keeps the ratchet self-contained so it cannot silently compare
          # nothing if the coverage test is ever bypassed or weakened.
          is_nil(pc) or is_nil(cc) ->
            "#{surface}.#{theme}: missing cell " <>
              "(prior=#{inspect(pc)}, current=#{inspect(cc)})"

          cc["total"] > pc["total"] ->
            "#{surface}.#{theme}: total #{pc["total"]} → #{cc["total"]} (REGRESSION)"

          # Fail closed when a present cell carries a non-zero total but a
          # missing/non-map `rules` map: a producer bug emitting
          # `{total: 2, rules: null}` would otherwise pass clean (the rising-total
          # branch above only fires when the total itself rose), masking a rule
          # swap that lost its per-rule detail (WR-03). A genuinely clean cell is
          # `{total: 0, rules: {}}`, so only guard non-zero totals.
          cc["total"] > 0 and not is_map(cc["rules"]) ->
            "#{surface}.#{theme}: current rules map missing/non-map under " <>
              "total #{inspect(cc["total"])} (cannot diff — REGRESSION)"

          true ->
            # Per-rule diff: fail closed when ANY rule's count rises OR a rule-id
            # present in current is absent in prior (even if total held flat — a
            # rule swap masks under a flat total otherwise).
            rule_regressions =
              for {rid, ccount} <- cc["rules"] || %{} do
                pcount = get_in(pc, ["rules", rid]) || 0

                if ccount > pcount,
                  do: "#{surface}.#{theme}: #{rid} #{pcount} → #{ccount} (REGRESSION)",
                  else: nil
              end
              |> Enum.reject(&is_nil/1)

            if rule_regressions == [], do: nil, else: Enum.join(rule_regressions, "\n")
        end
      end
      |> List.flatten()
      |> Enum.reject(&is_nil/1)

    assert regressions == [],
           "Axe violation regressions (#{length(regressions)}) — " <>
             "only-forward ratchet violated:\n" <>
             Enum.join(regressions, "\n") <>
             "\nEach cell must meet or beat the prior committed baseline " <>
             "(per total AND per rule-id)."
  end
end
