name: Actionlint

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Lint workflow files
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca
